version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-app
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./public/uploads:/srv/app/public/uploads
      - ./config:/srv/app/config
    environment:
      NODE_ENV: production
      TRUST_PROXY: true
      STRAPI_URL: https://сервер.три-клопа.рф
      PUBLIC_URL: https://сервер.три-клопа.рф
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
